<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOBSNIPw\srcApp_KernelDebugDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOBSNIPw/srcApp_KernelDebugDebugContainer.php') {
    touch(__DIR__.'/ContainerOBSNIPw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDebugDebugContainer::class, false)) {
    \class_alias(\ContainerOBSNIPw\srcApp_KernelDebugDebugContainer::class, srcApp_KernelDebugDebugContainer::class, false);
}

return new \ContainerOBSNIPw\srcApp_KernelDebugDebugContainer([
    'container.build_hash' => 'OBSNIPw',
    'container.build_id' => '660b35c2',
    'container.build_time' => 1583414594,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOBSNIPw');
