<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'mrBin_home' => [[], ['_controller' => 'App\\Controller\\HomeController::main'], [], [['text', '/']], [], []],
];
