<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Categories extends \App\Entity\Categories implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'nomCategorie', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'dechetCommun', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'typeDechets', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'url_picto', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'etablissements'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'nomCategorie', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'dechetCommun', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'typeDechets', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'url_picto', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'etablissements'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Categories $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomCategorie(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomCategorie', []);

        return parent::getNomCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomCategorie(string $nomCategorie): \App\Entity\Categories
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomCategorie', [$nomCategorie]);

        return parent::setNomCategorie($nomCategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getDechetCommun(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDechetCommun', []);

        return parent::getDechetCommun();
    }

    /**
     * {@inheritDoc}
     */
    public function setDechetCommun(?bool $dechetCommun): \App\Entity\Categories
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDechetCommun', [$dechetCommun]);

        return parent::setDechetCommun($dechetCommun);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeDechets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeDechets', []);

        return parent::getTypeDechets();
    }

    /**
     * {@inheritDoc}
     */
    public function addTypeDechet(\App\Entity\TypeDechet $typeDechet): \App\Entity\Categories
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTypeDechet', [$typeDechet]);

        return parent::addTypeDechet($typeDechet);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTypeDechet(\App\Entity\TypeDechet $typeDechet): \App\Entity\Categories
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTypeDechet', [$typeDechet]);

        return parent::removeTypeDechet($typeDechet);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlPicto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlPicto', []);

        return parent::getUrlPicto();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlPicto(?string $url_picto): \App\Entity\Categories
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlPicto', [$url_picto]);

        return parent::setUrlPicto($url_picto);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\Categories
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtablissements(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtablissements', []);

        return parent::getEtablissements();
    }

    /**
     * {@inheritDoc}
     */
    public function addEtablissement(\App\Entity\Etablissement $etablissement): \App\Entity\Categories
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEtablissement', [$etablissement]);

        return parent::addEtablissement($etablissement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEtablissement(\App\Entity\Etablissement $etablissement): \App\Entity\Categories
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEtablissement', [$etablissement]);

        return parent::removeEtablissement($etablissement);
    }

}
